[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.20.8"
  NEXTAUTH_URL = "https://your-app-name.netlify.app"
  NEXTAUTH_SECRET = "WeyFnOSmnQHV2kkuwyHiwoxD2xMQr6rwTlAlNpxlTX0="
  DATABASE_URL = "postgresql://dummy:dummy@localhost:5432/dummy"
  NEXT_PUBLIC_SUPABASE_URL = "https://dummy.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "dummy-anon-key"
  SUPABASE_SERVICE_ROLE_KEY = "dummy-service-key"
  RESEND_API_KEY = "dummy-resend-key"
  NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true
