name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build
      env:
        NEXTAUTH_URL: https://ryo-yz24.github.io/keihiseisan
        NEXTAUTH_SECRET: WeyFnOSmnQHV2kkuwyHiwoxD2xMQr6rwTlAlNpxlTX0=
        DATABASE_URL: postgresql://dummy:dummy@localhost:5432/dummy
        NEXT_PUBLIC_SUPABASE_URL: https://dummy.supabase.co
        NEXT_PUBLIC_SUPABASE_ANON_KEY: dummy-anon-key
        SUPABASE_SERVICE_ROLE_KEY: dummy-service-key
        NODE_ENV: production
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./.next
